[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }